services:
  - type: web
    name: hypesniff
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 900 --workers 1 --threads 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
